server:
  port: 9898

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus-first?serverTimezone=GMT%2b8
    username: root
    password: qwer1234

mybatis-plus:
  global-config:
    db-config:
      id-type: auto # id自增长配置，不用再每个实体每个主键单独配置。
#      table-prefix: tb_ # 表名前缀，相当于@TableName("tb_user")
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql日志打印
  mapper-locations: classpath:mapper/*.xml  #自定义方法映射的sqlmapper文件路径
  type-aliases-package: roydon.xyz.mybatisplusdemo.entity
